Export dbus address for the notification server
QubesOS/qubes-video-companion pull request #23
Opened 2024-05-30 21:48 UTC by ben-grande

Only screenshare script requires as of today, but put it in webcam also for future proof as it doesn't cause any harm.

Assigning variable and declaration made separate due to ShellCheck warning SC2155.

For: https://github.com/QubesOS/qubes-issues/issues/6426
Fixes: https://github.com/QubesOS/qubes-issues/issues/8457
Fixes: https://github.com/QubesOS/qubes-video-companion/issues/15

2024-05-30 21:54 UTC, DemiMarie commented on qubes-rpc/services/qvc.ScreenShare
> +export DISPLAY DBUS_SESSION_BUS_ADDRESS
```suggestion
set -eu
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
export DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS
```

2024-05-30 21:54 UTC, DemiMarie commented on qubes-rpc/services/qvc.Webcam
> +export DISPLAY DBUS_SESSION_BUS_ADDRESS
```suggestion
set -eu
DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$(id -u)/bus"
export DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS
```

2024-05-30 21:55 UTC, DemiMarie commented
Should `$XDG_RUNTIME_DIR` also be set?

2024-05-31 06:30 UTC, ben-grande commented
> Should `$XDG_RUNTIME_DIR` also be set?

Not necessary but nice to have and be the base path of DBUS_SESSION_BUS_ADDRESS. Will do.

2024-05-31 11:16 UTC, marmarek requested changes
Don't override those unconditionally. Set only if not present already.
Especially, if user session is running (and so is qrexec-fork-server), they should be provided already. There may be cases when either of them have different value (like in GUI domain that runs full desktop env)

2024-05-31 12:37 UTC, ben-grande commented
> Don't override those unconditionally. Set only if not present already.

Done.

> Especially, if user session is running (and so is qrexec-fork-server), they should be provided already. There may be cases when either of them have different value (like in GUI domain that runs full desktop env)

Unfortunately they were not set and many users, including me, encountered that issue. Now it is using the existent value if set, else fallback.

2024-05-31 12:49 UTC, marmarek approved these changes

2024-05-31 12:49 UTC, merged