Allow the receiver to request a preferred resolution
QubesOS/qubes-video-companion pull request #8
Opened 2023-08-16 00:03 UTC by DemiMarie

The sender tries to find a resolution that is close to the preferred one of the receiver.

2023-08-20 01:06 UTC, marmarek commented
PipelineRetry

2023-09-10 23:28 UTC, marmarek requested changes
Please add also setting the argument in `qubes-video-companion` script. Something like `qubes-video-companion --resolution w+h+f webcam` , maybe also with short option `-r` and maybe for convenience also with replacing `x` and `@` with `+`, so one can write `800x600@30` (but please, keep it simple, no complex regexes).

2023-09-10 23:28 UTC, marmarek commented on sender/webcam.py
> +            untrusted_arg_bytes = untrusted_arg.encode('ascii', 'strict')
You've got `str` already, there is no point in converting back to bytes.

2024-03-14 00:36 UTC, marmarek commented
> Please add also setting the argument in `qubes-video-companion` script. Something like `qubes-video-companion --resolution w+h+f webcam` , maybe also with short option `-r` and maybe for convenience also with replacing `x` and `@` with `+`, so one can write `800x600@30` (but please, keep it simple, no complex regexes).

Ping?

2024-03-14 03:19 UTC, DemiMarie commented
> > Please add also setting the argument in `qubes-video-companion` script. Something like `qubes-video-companion --resolution w+h+f webcam` , maybe also with short option `-r` and maybe for convenience also with replacing `x` and `@` with `+`, so one can write `800x600@30` (but please, keep it simple, no complex regexes).
> 
> Ping?

I just pushed a version that implements it.  I’ll start testing it, but I wanted to get this out there first.

2024-03-14 13:28 UTC, marmarek requested changes

2024-03-14 13:28 UTC, marmarek commented on receiver/qubes-video-companion
> +if getopt -T > /dev/null; then unsupported_getopt; elif [ "$?" -ne 4 ]; then unsupported_getopt; fi
The intended use does not require any spaces in arguments, so I think this check is overzealous (I know **incorrect** use with no quoting would result in a weird error, but I don't think it's really relevant).

2024-03-14 13:28 UTC, marmarek commented on receiver/qubes-video-companion
> +    printf '%s: Usage: qubes-video-companion webcam|screenshare [destination qube]\n' "$name"
You did changed this line in the recent push, yet you did not added the new option...

2024-03-28 05:28 UTC, marmarek commented
Shellcheck complains

2024-03-29 14:34 UTC, marmarek commented
It doesn't work for me. I did `qubes-video-companion -r 320x240 webcam`, double checked it indeed got included in the service argument, yet I received 1920x1080 stream.
Formats supported by that camera:
```
ioctl: VIDIOC_ENUM_FMT
        Type: Video Capture

        [0]: 'MJPG' (Motion-JPEG, compressed)
                Size: Discrete 1920x1080
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 320x180
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 320x240
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 424x240
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 640x360
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 640x480
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 848x480
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 960x540
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 1280x720
                        Interval: Discrete 0.017s (60.000 fps)
                        Interval: Discrete 0.033s (30.000 fps)
        [1]: 'YUYV' (YUYV 4:2:2)
                Size: Discrete 1920x1080
                        Interval: Discrete 0.200s (5.000 fps)
                Size: Discrete 320x180
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 320x240
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 424x240
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 640x360
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 640x480
                        Interval: Discrete 0.033s (30.000 fps)
                Size: Discrete 848x480
                        Interval: Discrete 0.050s (20.000 fps)
                Size: Discrete 960x540
                        Interval: Discrete 0.067s (15.000 fps)
                Size: Discrete 1280x720
                        Interval: Discrete 0.125s (8.000 fps)
```

2024-03-29 22:41 UTC, DemiMarie commented
The shell script wrapper was not passing the argument to the Python script.  Now fixed.

2024-04-02 23:50 UTC, marmarek commented
Convert to non-draft?

2024-04-02 23:51 UTC, DemiMarie commented
done

2024-04-03 16:11 UTC, marmarek approved these changes

2024-04-03 16:12 UTC, merged