Add missing 'acl' dependency
QubesOS/qubes-video-companion pull request #9
Opened 2023-08-17 14:17 UTC by DemiMarie

Needed for setfacl call in receiver script.

Fixes: QubesOS/qubes-issues#8426

2023-08-19 17:20 UTC, DemiMarie commented
PipelineRetryFailed

2023-08-19 17:49 UTC, DemiMarie commented
PipelineRetry

2023-08-19 23:02 UTC, marmarek commented
PipelineRetry

2023-09-10 23:30 UTC, marmarek requested changes

2023-09-10 23:30 UTC, marmarek commented on rpm_spec/qubes-video-companion.spec.in
> +Requires:       acl
It's the receiver that uses setfacl, not the sender.

2023-09-14 22:12 UTC, marmarek approved these changes

2023-09-14 22:12 UTC, merged